apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "guest",
          "password_hash": "20oei+PKrOxnBTmQWho5PQf29+aYovT7mw3tj+Sk4PG8Upwa",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [],
      "parameters": [],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": "micropic@fd2be0bb70ef"
        }
      ],
      "policies": [],
      "queues": [],
      "exchanges": [
        {
          "name": "micropic",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "no_wait": false,
          "arguments": {}
        }
      ],
      "bindings": []
    }