# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  go: circleci/go@1.1.1

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
#      - go/load-cache
      - go/mod-download
#      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          count: '5'
          race: true

# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - build
