apiVersion: v1
kind: Service
metadata:
  name: previewer # SERVICE_NAME
  labels:
    # we pass selector, to list specific Services:
    # kubectl get svc --selector=KEY_SERVICE_SELECTOR
    app: previewer # KEY_SERVICE_SELECTOR: VALUE_SERVICE_SELECTOR
spec:
  type: ClusterIP # options: ClusterIP, NodePort, LoadBalancer, ExternalName
  selector:
    # thanks to this selector, we specify,
    # to which Pods the Service should forward the traffic
    app: previewer # KEY_POD_SELECTOR: VALUE_POD_SELECTOR
