---
previewer:
  quality: 70

amqp:
  protocol: "amqp"
  user: "guest"
  password: "guest"
  host: "127.0.0.1"
  port: 5672

grpc:
  host: "127.0.0.1"
  port: 9090

log:
  file: ./previewer.log
  level: debug
