---
proxy:
  host: "0.0.0.0"
  port: 8080
  timeout: 5

amqp:
  protocol: "amqp"
  user: "guest"
  password: "guest"
  host: "127.0.0.1"
  port: 5672

grpc:
  host: "127.0.0.1"
  port: 50051

log:
  file: ./proxy.log
  level: debug

health:
  port: 8000